name: Update Feeds

on:
  schedule:
    - cron: "*/30 * * * *"      # Every 30 minutes (master feed)
    - cron: "0 3 * * *"         # Every day at 9:00 AM Bangladesh Time (3:00 AM UTC)
  workflow_dispatch:             # Optional manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install feedparser

      # 4️⃣ Run main script
      - name: Run main.py
        run: |
          python main.py

      # 5️⃣ Commit & push updated XMLs safely
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Only add files if they exist
          git add feed_master.xml last_seen.json || true
          if [ -f daily_feed.xml ]; then git add daily_feed.xml; fi
          
          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto update feeds"
            git push
          fi